### ISSUE TITLE
Cannot read property 'dense' of undefined in development env

### ISSUE THREAD

**Issue by chnliquan** [ctrlplusb/react-async-bootstrapper#15]
I use [](https://github.com/mui-org/material-ui) + react-async-bootstrapper for react ssr development, it will report an error in the development environment, the production environment is normal, how should this problem be solved, thank you

```
"TypeError: Cannot read property 'dense' of undefined\n   
 at Object.children (server-entry.js:29:31469)\n    
at recursive (/Users/ender/learning/github/react-cnode/node_modules/react-tree-walker/dist/react-tree-walker.js:129:41)\n   
 at /Users/ender/learning/github/react-cnode/node_modules/react-tree-walker/dist/react-tree-walker.js:153:26\n   
 at <anonymous>\n   
 at process._tickCallback (internal/process/next_tick.js:189:7)"
```

**Comment by 0-Captain** [comment]
I miss the error too. Did you solve it?
